 DROP SCHEMA AIRLINE_RESERVATION_SYSTEM;
CREATE SCHEMA AIRLINE_RESERVATION_SYSTEM;
SET GLOBAL default_storage_engine =INNODB;
use AIRLINE_RESERVATION_SYSTEM;
CREATE TABLE AEREO (
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60),
FLIGHTS_FLOWN LONG,
MANTEINANCE_DUE BOOLEAN
);
CREATE TABLE CLIENTE (
 ID INTEGER PRIMARY KEY auto_increment,
 NOME VARCHAR(30),
 COGNOME VARCHAR(30),
 INDIRIZZO VARCHAR(45),
 FEDELTA BOOL,
 EMAIL VARCHAR(30) UNIQUE,
 PUNTI_ACCUMULATI BIGINT DEFAULT 0,
 PASSWORD_HASH varchar(256),
  DATA_NASCITA DATETIME
);
CREATE TABLE CITTA(
 NOME VARCHAR(40) PRIMARY KEY,
 STATO TEXT
);
CREATE TABLE VOLO(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
PARTENZA VARCHAR(40),
DESTINAZIONE VARCHAR(40),
DATA_PARTENZA DATETIME, 
AEREO integer,
AEREOPORTO TEXT, 
TARIFFA_FIRST FLOAT,
TARIFFA_BUSINESS FLOAT,
TARIFFA_ECONOMY FLOAT,
MIGLIA INTEGER,
GATE INTEGER,
FOREIGN KEY (AEREO) REFERENCES AEREO(ID),
FOREIGN KEY (PARTENZA) REFERENCES CITTA(NOME),
FOREIGN KEY (DESTINAZIONE) REFERENCES CITTA(NOME)
);
CREATE TABLE PRENOTAZIONE(
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
VOLO INTEGER,
CLIENTE INTEGER, 
PUNTI_GUADAGNATI INTEGER,
CHECK_IN_EFFETTUATO BOOLEAN,
PRICE_PAID FLOAT,
UNIQUE(VOLO,CLIENTE),
FOREIGN KEY (VOLO) REFERENCES VOLO(ID),
FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID)
);
CREATE TABLE POSTO(
	ID INTEGER  AUTO_INCREMENT,
    AEREO INTEGER,
    CLASSE VARCHAR(50),
    PRIMARY KEY (ID,AEREO),
    FOREIGN KEY(AEREO) REFERENCES AEREO(ID)
);
CREATE TABLE POSTI_PRENOTATI(
 ID_PRENOTAZIONE INTEGER,
 POSTO_PRENOTATO INTEGER,
 CLIENTE INTEGER,
 VOLO INTEGER,
 PRIMARY KEY (VOLO,POSTO_PRENOTATO),
 FOREIGN KEY (ID_PRENOTAZIONE) REFERENCES PRENOTAZIONE(ID),
  FOREIGN KEY (VOLO) REFERENCES VOLO(ID),
 FOREIGN KEY (POSTO_PRENOTATO) REFERENCES POSTO(ID),
  FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID)
);
CREATE TABLE PRENOTAZIONE_NOTIFIED(
ID INTEGER  PRIMARY KEY,
DUE_DATE DATETIME,
CLIENTS_HAVE_BEEN_NOTIFIED BOOLEAN DEFAULT FALSE,
FOREIGN KEY (ID) REFERENCES PRENOTAZIONE(ID)
);
CREATE TABLE PROMOZIONI(
CODICE INTEGER PRIMARY KEY AUTO_INCREMENT,
FEDELTA_ONLY BOOLEAN,
INIZIO DATETIME,
FINE DATETIME,
PERCENTUALE_SCONTO FLOAT,
EMAIL_SENT BOOLEAN DEFAULT FALSE,
SUMMARY TEXT
);
CREATE TABLE VOLO_PROMO(
CODICE_PROMO INTEGER,
CODICE_VOLO INTEGER,
PRIMARY KEY (CODICE_PROMO,CODICE_VOLO),
FOREIGN KEY (CODICE_PROMO) REFERENCES PROMOZIONI(CODICE),
FOREIGN KEY (CODICE_VOLO) REFERENCES VOLO(ID)
);

